import "../../styles/base.css";
import { initHeartRate } from "./heart-rate.js";
import { initMenu } from "./menu.js";
import { initTerrain } from "./terrain-3d.js";
import { initArteFlujo } from "./arte-flujo.js";
import { initVisualizador } from "./visualizador-3d.js";
import { initCatalogo } from "./catalogo.js";
import { initCapas } from "./capas-3d.js";
import { initHeartbeatAudio } from "./heartbeat-audio.js";
import { initMicrophones } from "./microphones.js";
import { initJoystick } from "./joystick.js";
import { initDevices } from "./devices.js";

initHeartRate();
initMenu();
initTerrain();
initArteFlujo();
initVisualizador();
initCatalogo();
initCapas();
initHeartbeatAudio();
initMicrophones();
initJoystick();
initDevices();
